- name: put systemd unit file
  template: src=hadoop-jobhistoryserver.service.j2 dest=/etc/systemd/system/hadoop-jobhistoryserver.service owner=root group=root mode=0644

- name: reload systemd
  shell: systemctl daemon-reload 

- name: start hadoop-jobhistoryserver.service 
  service: name=hadoop-jobhistoryserver.service enabled=yes state=restarted
